export interface CountryRegionData {
  state: string;
  cities: string[];
}

/** India — all states & union territories with major cities */
export const INDIA_REGIONS: CountryRegionData[] = [
  { state: "Andhra Pradesh", cities: ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Tirupati", "Kurnool"] },
  { state: "Arunachal Pradesh", cities: ["Itanagar", "Tawang", "Pasighat", "Ziro", "Bomdila"] },
  { state: "Assam", cities: ["Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Tezpur", "Nagaon"] },
  { state: "Bihar", cities: ["Patna", "Gaya", "Muzaffarpur", "Bhagalpur", "Darbhanga", "Purnia"] },
  { state: "Chhattisgarh", cities: ["Raipur", "Bhilai", "Bilaspur", "Korba", "Durg", "Raigarh"] },
  { state: "Goa", cities: ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda"] },
  { state: "Gujarat", cities: ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar", "Gandhinagar"] },
  { state: "Haryana", cities: ["Gurugram", "Faridabad", "Panipat", "Ambala", "Karnal", "Hisar", "Rohtak"] },
  { state: "Himachal Pradesh", cities: ["Shimla", "Dharamshala", "Manali", "Solan", "Mandi", "Kullu"] },
  { state: "Jharkhand", cities: ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Deoghar", "Hazaribagh"] },
  { state: "Karnataka", cities: ["Bangalore", "Mysore", "Mangalore", "Hubli", "Belgaum", "Davangere", "Shimoga"] },
  { state: "Kerala", cities: ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam", "Kannur", "Palakkad"] },
  { state: "Madhya Pradesh", cities: ["Bhopal", "Indore", "Jabalpur", "Gwalior", "Ujjain", "Sagar", "Ratlam"] },
  { state: "Maharashtra", cities: ["Mumbai", "Pune", "Nagpur", "Nashik", "Thane", "Aurangabad", "Solapur", "Kolhapur"] },
  { state: "Manipur", cities: ["Imphal", "Thoubal", "Bishnupur", "Churachandpur", "Ukhrul"] },
  { state: "Meghalaya", cities: ["Shillong", "Tura", "Jowai", "Nongpoh", "Williamnagar"] },
  { state: "Mizoram", cities: ["Aizawl", "Lunglei", "Champhai", "Serchhip", "Kolasib"] },
  { state: "Nagaland", cities: ["Kohima", "Dimapur", "Mokokchung", "Tuensang", "Wokha"] },
  { state: "Odisha", cities: ["Bhubaneswar", "Cuttack", "Rourkela", "Berhampur", "Sambalpur", "Puri"] },
  { state: "Punjab", cities: ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Mohali", "Pathankot"] },
  { state: "Rajasthan", cities: ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Ajmer", "Bikaner", "Alwar"] },
  { state: "Sikkim", cities: ["Gangtok", "Namchi", "Gyalshing", "Mangan", "Rangpo"] },
  { state: "Tamil Nadu", cities: ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Tirunelveli", "Erode"] },
  { state: "Telangana", cities: ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Khammam", "Ramagundam"] },
  { state: "Tripura", cities: ["Agartala", "Udaipur (Tripura)", "Dharmanagar", "Kailashahar", "Belonia"] },
  { state: "Uttar Pradesh", cities: ["Lucknow", "Kanpur", "Ghaziabad", "Agra", "Varanasi", "Meerut", "Prayagraj", "Noida"] },
  { state: "Uttarakhand", cities: ["Dehradun", "Haridwar", "Rishikesh", "Haldwani", "Roorkee", "Nainital"] },
  { state: "West Bengal", cities: ["Kolkata", "Howrah", "Durgapur", "Asansol", "Siliguri", "Darjeeling", "Kharagpur"] },
  { state: "Andaman and Nicobar Islands", cities: ["Port Blair", "Diglipur", "Rangat", "Mayabunder"] },
  { state: "Chandigarh", cities: ["Chandigarh"] },
  { state: "Dadra and Nagar Haveli and Daman and Diu", cities: ["Daman", "Diu", "Silvassa"] },
  { state: "Delhi", cities: ["New Delhi", "North Delhi", "South Delhi", "East Delhi", "West Delhi"] },
  { state: "Jammu and Kashmir", cities: ["Srinagar", "Jammu", "Anantnag", "Baramulla", "Udhampur"] },
  { state: "Ladakh", cities: ["Leh", "Kargil", "Nubra", "Diskit"] },
  { state: "Lakshadweep", cities: ["Kavaratti", "Agatti", "Minicoy", "Amini"] },
  { state: "Puducherry", cities: ["Puducherry", "Karaikal", "Mahe", "Yanam"] },
];

/** Canada — all provinces & territories */
export const CANADA_REGIONS: CountryRegionData[] = [
  { state: "Alberta", cities: ["Calgary", "Edmonton", "Red Deer", "Lethbridge", "Medicine Hat", "Grande Prairie"] },
  { state: "British Columbia", cities: ["Vancouver", "Victoria", "Surrey", "Burnaby", "Kelowna", "Kamloops", "Richmond"] },
  { state: "Manitoba", cities: ["Winnipeg", "Brandon", "Steinbach", "Thompson", "Portage la Prairie"] },
  { state: "New Brunswick", cities: ["Fredericton", "Moncton", "Saint John", "Bathurst", "Miramichi"] },
  { state: "Newfoundland and Labrador", cities: ["St. John's", "Corner Brook", "Gander", "Grand Falls-Windsor", "Labrador City"] },
  { state: "Nova Scotia", cities: ["Halifax", "Dartmouth", "Sydney", "Truro", "New Glasgow"] },
  { state: "Ontario", cities: ["Toronto", "Ottawa", "Mississauga", "Brampton", "Hamilton", "London", "Kitchener", "Windsor"] },
  { state: "Prince Edward Island", cities: ["Charlottetown", "Summerside", "Stratford", "Cornwall"] },
  { state: "Quebec", cities: ["Montreal", "Quebec City", "Laval", "Gatineau", "Longueuil", "Sherbrooke", "Saguenay"] },
  { state: "Saskatchewan", cities: ["Saskatoon", "Regina", "Prince Albert", "Moose Jaw", "Swift Current"] },
  { state: "Northwest Territories", cities: ["Yellowknife", "Hay River", "Inuvik", "Fort Smith"] },
  { state: "Nunavut", cities: ["Iqaluit", "Rankin Inlet", "Arviat", "Cambridge Bay"] },
  { state: "Yukon", cities: ["Whitehorse", "Dawson City", "Watson Lake", "Haines Junction"] },
];

/** USA — all 50 states */
export const USA_REGIONS: CountryRegionData[] = [
  { state: "Alabama", cities: ["Birmingham", "Montgomery", "Huntsville", "Mobile", "Tuscaloosa"] },
  { state: "Alaska", cities: ["Anchorage", "Fairbanks", "Juneau", "Sitka", "Ketchikan"] },
  { state: "Arizona", cities: ["Phoenix", "Tucson", "Mesa", "Chandler", "Scottsdale", "Glendale"] },
  { state: "Arkansas", cities: ["Little Rock", "Fort Smith", "Fayetteville", "Springdale", "Jonesboro"] },
  { state: "California", cities: ["Los Angeles", "San Francisco", "San Diego", "San Jose", "Sacramento", "Fresno", "Oakland"] },
  { state: "Colorado", cities: ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Boulder"] },
  { state: "Connecticut", cities: ["Bridgeport", "New Haven", "Hartford", "Stamford", "Waterbury"] },
  { state: "Delaware", cities: ["Wilmington", "Dover", "Newark", "Middletown", "Smyrna"] },
  { state: "Florida", cities: ["Miami", "Orlando", "Tampa", "Jacksonville", "Fort Lauderdale", "Tallahassee"] },
  { state: "Georgia", cities: ["Atlanta", "Augusta", "Columbus", "Savannah", "Athens", "Macon"] },
  { state: "Hawaii", cities: ["Honolulu", "Hilo", "Kailua", "Kapolei", "Pearl City"] },
  { state: "Idaho", cities: ["Boise", "Meridian", "Nampa", "Idaho Falls", "Pocatello"] },
  { state: "Illinois", cities: ["Chicago", "Aurora", "Naperville", "Joliet", "Rockford", "Springfield"] },
  { state: "Indiana", cities: ["Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Carmel"] },
  { state: "Iowa", cities: ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City", "Iowa City"] },
  { state: "Kansas", cities: ["Wichita", "Overland Park", "Kansas City", "Topeka", "Olathe"] },
  { state: "Kentucky", cities: ["Louisville", "Lexington", "Bowling Green", "Owensboro", "Covington"] },
  { state: "Louisiana", cities: ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette", "Lake Charles"] },
  { state: "Maine", cities: ["Portland", "Lewiston", "Bangor", "South Portland", "Auburn"] },
  { state: "Maryland", cities: ["Baltimore", "Frederick", "Rockville", "Gaithersburg", "Annapolis"] },
  { state: "Massachusetts", cities: ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell", "New Bedford"] },
  { state: "Michigan", cities: ["Detroit", "Grand Rapids", "Ann Arbor", "Lansing", "Flint", "Dearborn"] },
  { state: "Minnesota", cities: ["Minneapolis", "Saint Paul", "Rochester", "Duluth", "Bloomington"] },
  { state: "Mississippi", cities: ["Jackson", "Gulfport", "Southaven", "Hattiesburg", "Biloxi"] },
  { state: "Missouri", cities: ["Kansas City", "St. Louis", "Springfield", "Columbia", "Independence"] },
  { state: "Montana", cities: ["Billings", "Missoula", "Great Falls", "Bozeman", "Helena"] },
  { state: "Nebraska", cities: ["Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney"] },
  { state: "Nevada", cities: ["Las Vegas", "Henderson", "Reno", "North Las Vegas", "Sparks"] },
  { state: "New Hampshire", cities: ["Manchester", "Nashua", "Concord", "Dover", "Rochester"] },
  { state: "New Jersey", cities: ["Newark", "Jersey City", "Paterson", "Elizabeth", "Trenton", "Atlantic City"] },
  { state: "New Mexico", cities: ["Albuquerque", "Las Cruces", "Santa Fe", "Rio Rancho", "Roswell"] },
  { state: "New York", cities: ["New York City", "Buffalo", "Rochester", "Syracuse", "Albany", "Yonkers"] },
  { state: "North Carolina", cities: ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem", "Asheville"] },
  { state: "North Dakota", cities: ["Fargo", "Bismarck", "Grand Forks", "Minot", "West Fargo"] },
  { state: "Ohio", cities: ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron", "Dayton"] },
  { state: "Oklahoma", cities: ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Edmond"] },
  { state: "Oregon", cities: ["Portland", "Salem", "Eugene", "Gresham", "Bend", "Hillsboro"] },
  { state: "Pennsylvania", cities: ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading", "Harrisburg"] },
  { state: "Rhode Island", cities: ["Providence", "Warwick", "Cranston", "Pawtucket", "Newport"] },
  { state: "South Carolina", cities: ["Charleston", "Columbia", "North Charleston", "Greenville", "Myrtle Beach"] },
  { state: "South Dakota", cities: ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings", "Watertown"] },
  { state: "Tennessee", cities: ["Nashville", "Memphis", "Knoxville", "Chattanooga", "Clarksville"] },
  { state: "Texas", cities: ["Houston", "Dallas", "Austin", "San Antonio", "Fort Worth", "El Paso", "Arlington"] },
  { state: "Utah", cities: ["Salt Lake City", "West Valley City", "Provo", "West Jordan", "Orem", "St. George"] },
  { state: "Vermont", cities: ["Burlington", "South Burlington", "Rutland", "Montpelier", "Barre"] },
  { state: "Virginia", cities: ["Virginia Beach", "Norfolk", "Richmond", "Arlington", "Alexandria", "Chesapeake"] },
  { state: "Washington", cities: ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue", "Olympia"] },
  { state: "West Virginia", cities: ["Charleston", "Huntington", "Morgantown", "Parkersburg", "Wheeling"] },
  { state: "Wisconsin", cities: ["Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine", "Appleton"] },
  { state: "Wyoming", cities: ["Cheyenne", "Casper", "Laramie", "Gillette", "Rock Springs"] },
];

/** UK — constituent countries & regions */
export const UK_REGIONS: CountryRegionData[] = [
  { state: "Greater London", cities: ["City of London", "Westminster", "Camden", "Greenwich", "Hackney", "Croydon", "Bromley"] },
  { state: "South East England", cities: ["Brighton", "Oxford", "Reading", "Southampton", "Portsmouth", "Milton Keynes"] },
  { state: "South West England", cities: ["Bristol", "Plymouth", "Bournemouth", "Exeter", "Bath", "Gloucester"] },
  { state: "East of England", cities: ["Cambridge", "Norwich", "Ipswich", "Luton", "Peterborough", "Chelmsford"] },
  { state: "West Midlands", cities: ["Birmingham", "Coventry", "Wolverhampton", "Stoke-on-Trent", "Worcester"] },
  { state: "East Midlands", cities: ["Nottingham", "Leicester", "Derby", "Northampton", "Lincoln"] },
  { state: "Yorkshire and the Humber", cities: ["Leeds", "Sheffield", "Bradford", "Hull", "York", "Doncaster"] },
  { state: "North West England", cities: ["Manchester", "Liverpool", "Preston", "Blackpool", "Chester", "Lancaster"] },
  { state: "North East England", cities: ["Newcastle upon Tyne", "Sunderland", "Durham", "Middlesbrough", "Gateshead"] },
  { state: "Scotland", cities: ["Edinburgh", "Glasgow", "Aberdeen", "Dundee", "Inverness", "Stirling", "Perth"] },
  { state: "Wales", cities: ["Cardiff", "Swansea", "Newport", "Wrexham", "Bangor", "Aberystwyth"] },
  { state: "Northern Ireland", cities: ["Belfast", "Derry", "Lisburn", "Newry", "Armagh", "Bangor"] },
];

/** Singapore — regions & planning areas */
export const SINGAPORE_REGIONS: CountryRegionData[] = [
  {
    state: "Central Region",
    cities: [
      "Orchard",
      "Marina Bay",
      "Bugis",
      "Chinatown",
      "Little India",
      "Novena",
      "Bukit Timah",
      "River Valley",
    ],
  },
  {
    state: "East Region",
    cities: ["Tampines", "Bedok", "Pasir Ris", "Changi", "Katong", "Marine Parade", "Geylang"],
  },
  {
    state: "North Region",
    cities: ["Woodlands", "Yishun", "Sembawang", "Admiralty", "Mandai", "Kranji"],
  },
  {
    state: "North-East Region",
    cities: ["Hougang", "Punggol", "Sengkang", "Serangoon", "Ang Mo Kio", "Bishan"],
  },
  {
    state: "West Region",
    cities: ["Jurong East", "Jurong West", "Bukit Batok", "Clementi", "Boon Lay", "Choa Chu Kang", "Tuas"],
  },
];
